services:

  app:
    container_name: todo-laravel
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 5000:80
  
  mysql_db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    ports:
      - 3000:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1