services:

  app:
    container_name: todo-laravel
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 5000:8000
    depends_on:
      - mysql
      
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo-app
    ports:
      - 3000:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  mysql_test:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo-app-test
    ports:
      - 3001:3306
    volumes:
      - mysql_test:/var/lib/mysql
      - ./test.sql:/docker-entrypoint-initdb.d/test.sql
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql:
    driver: local
  mysql_test:
    driver: local
  
